// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: htABaZqjni3rpeuBprLs6a
// Component: 9p-Ht8_FObo03_

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: Z2-bJBY1mYy2V/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_interactions_tutorial.module.css"; // plasmic-import: htABaZqjni3rpeuBprLs6a/projectcss
import sty from "./PlasmicStep4.module.css"; // plasmic-import: 9p-Ht8_FObo03_/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 3x-g38V1yDuQmW/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: OR1sp1EE4k9P8M/icon

export type PlasmicStep4__VariantMembers = {};
export type PlasmicStep4__VariantsArgs = {};
type VariantPropType = keyof PlasmicStep4__VariantsArgs;
export const PlasmicStep4__VariantProps = new Array<VariantPropType>();

export type PlasmicStep4__ArgsType = {};
type ArgPropType = keyof PlasmicStep4__ArgsType;
export const PlasmicStep4__ArgProps = new Array<ArgPropType>();

export type PlasmicStep4__OverridesType = {
  root?: p.Flex<"div">;
  button?: p.Flex<typeof Button>;
};

export interface DefaultStep4Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicStep4__RenderFunc(props: {
  variants: PlasmicStep4__VariantsArgs;
  args: PlasmicStep4__ArgsType;
  overrides: PlasmicStep4__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "earthAnswer",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "skyAnswer",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    <React.Fragment>
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.root
            )}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cI3Hw
              )}
            >
              {"FAQ"}
            </div>
            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames("__wab_instance", sty.button)}
              onClick={async event => {
                const $steps = {};
                $steps["setEarthAnswer"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "TagcJ1m1kL1OL",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["earthAnswer"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "TagcJ1m1kL1OL",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "operation"
                          },
                          () => 0
                        ),
                        value: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "TagcJ1m1kL1OL",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "value"
                          },
                          () => true
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "TagcJ1m1kL1OL",
                          componentUuid: "9p-Ht8_FObo03_"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            const { objRoot, variablePath } = variable;

                            p.set(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["setEarthAnswer"] === "object" &&
                  typeof $steps["setEarthAnswer"].then === "function"
                ) {
                  $steps["setEarthAnswer"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "TagcJ1m1kL1OL",
                      componentUuid: "9p-Ht8_FObo03_"
                    },
                    $steps["setEarthAnswer"]
                  );
                }
                $steps["setSkyAnswer"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "ns_bN5fUrBR5k",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["skyAnswer"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "ns_bN5fUrBR5k",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "operation"
                          },
                          () => 0
                        ),
                        value: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "ns_bN5fUrBR5k",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "value"
                          },
                          () => true
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "ns_bN5fUrBR5k",
                          componentUuid: "9p-Ht8_FObo03_"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            const { objRoot, variablePath } = variable;

                            p.set(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["setSkyAnswer"] === "object" &&
                  typeof $steps["setSkyAnswer"].then === "function"
                ) {
                  $steps["setSkyAnswer"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "ns_bN5fUrBR5k",
                      componentUuid: "9p-Ht8_FObo03_"
                    },
                    $steps["setSkyAnswer"]
                  );
                }
              }}
            >
              {"Switch all"}
            </Button>
            <div
              className={classNames(projectcss.all, sty.freeBox__ttRz)}
              onClick={async event => {
                const $steps = {};
                $steps["setEarthAnswer"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "KQBgYoiH3wMCg",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["earthAnswer"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "KQBgYoiH3wMCg",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "operation"
                          },
                          () => 4
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "KQBgYoiH3wMCg",
                          componentUuid: "9p-Ht8_FObo03_"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            const { objRoot, variablePath } = variable;

                            const oldValue = p.get(objRoot, variablePath);
                            p.set(objRoot, variablePath, !oldValue);
                            return !oldValue;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["setEarthAnswer"] === "object" &&
                  typeof $steps["setEarthAnswer"].then === "function"
                ) {
                  $steps["setEarthAnswer"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "KQBgYoiH3wMCg",
                      componentUuid: "9p-Ht8_FObo03_"
                    },
                    $steps["setEarthAnswer"]
                  );
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pRuXw
                )}
              >
                {"Question: Why is the earth round?"}
              </div>
              {(() => {
                try {
                  return $state.earthAnswer;
                } catch (e) {
                  if (e instanceof TypeError) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qaHub
                  )}
                >
                  {"Answer: Gravity"}
                </div>
              ) : null}
            </div>
            <div
              className={classNames(projectcss.all, sty.freeBox__mXIrK)}
              onClick={async event => {
                const $steps = {};
                $steps["setSkyAnswer"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "I9pmPQCx1jxo93",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["skyAnswer"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "I9pmPQCx1jxo93",
                            componentUuid: "9p-Ht8_FObo03_",
                            argName: "operation"
                          },
                          () => 4
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "I9pmPQCx1jxo93",
                          componentUuid: "9p-Ht8_FObo03_"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            const { objRoot, variablePath } = variable;

                            const oldValue = p.get(objRoot, variablePath);
                            p.set(objRoot, variablePath, !oldValue);
                            return !oldValue;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["setSkyAnswer"] === "object" &&
                  typeof $steps["setSkyAnswer"].then === "function"
                ) {
                  $steps["setSkyAnswer"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "I9pmPQCx1jxo93",
                      componentUuid: "9p-Ht8_FObo03_"
                    },
                    $steps["setSkyAnswer"]
                  );
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c2O4B
                )}
              >
                {"Question: Why is the sky blue?"}
              </div>
              {(() => {
                try {
                  return $state.skyAnswer;
                } catch (e) {
                  if (e instanceof TypeError) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qj35O
                  )}
                >
                  {"Answer: It's complicated"}
                </div>
              ) : null}
            </div>
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStep4__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStep4__VariantsArgs;
    args?: PlasmicStep4__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStep4__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStep4__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicStep4__ArgProps,
          internalVariantPropNames: PlasmicStep4__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStep4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStep4";
  } else {
    func.displayName = `PlasmicStep4.${nodeName}`;
  }
  return func;
}

export const PlasmicStep4 = Object.assign(
  // Top-level PlasmicStep4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicStep4
    internalVariantProps: PlasmicStep4__VariantProps,
    internalArgProps: PlasmicStep4__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStep4;
/* prettier-ignore-end */
